name: Build, Test for Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened,labeled]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Publish tagged PR
        if: >
          matrix.os == 'ubuntu-latest' &&
          github.event_name == 'pull_request' &&
          contains(github.event.pull_request.labels.*.name, 'tagged')
        continue-on-error: true
        run: |
          echo running on branch ${BRANCH_NAME}
          pnpm version:snapshot
          pnpm publish -r --tag ${BRANCH_NAME} --no-git-checks --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
